-- Drop previous tables if they exist (clean slate)
drop table if exists public.attacks;
drop table if exists public.websites;

-- Create single attacks table
create table public.attacks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Website/Target Details (Denormalized)
  target_url text not null, -- e.g., 'https://shop.example.com'
  target_name text, -- e.g., 'E-Commerce Store' (Optional, can be inferred or passed)
  
  -- Attack details
  type text not null, -- e.g., 'SQL Injection', 'XSS'
  severity text not null, -- 'critical', 'high', 'medium', 'low'
  ip_address text not null,
  status text not null, -- 'blocked', 'detected'
  payload text, 
  is_false_positive boolean default false,
  
  -- Metadata
  request_method text,
  user_agent text,
  path text
);

-- Enable RLS
alter table public.attacks enable row level security;

-- Policies
create policy "Allow public read access to attacks"
  on public.attacks for select
  to anon
  using (true);

create policy "Allow anon insert to attacks"
    on public.attacks for insert
    to anon
    with check (true);

create policy "Allow anon update to attacks"
    on public.attacks for update
    to anon
    using (true);

-- Indexes
create index attacks_target_url_idx on public.attacks(target_url);
create index attacks_created_at_idx on public.attacks(created_at);

-- Seed Data
insert into public.attacks (target_url, target_name, type, severity, ip_address, status, payload, created_at)
select 
  'https://shop.example.com',
  'E-Commerce Store',
  case floor(random() * 3)::int
    when 0 then 'SQL Injection'
    when 1 then 'XSS'
    else 'Command Injection'
  end as type,
  case floor(random() * 2)::int
    when 0 then 'critical'
    else 'high'
  end as severity,
  '192.168.1.' || floor(random() * 255)::text,
  'blocked',
  'Payload info...',
  now() - (interval '1 minute' * floor(random() * 1440))
from generate_series(1, 30);

insert into public.attacks (target_url, target_name, type, severity, ip_address, status, payload, created_at)
select 
  'https://portal.enterprise.co',
  'Corporate Portal',
  case floor(random() * 3)::int
    when 0 then 'SQL Injection'
    when 1 then 'XSS'
    else 'Command Injection'
  end as type,
  'medium',
  '10.0.0.' || floor(random() * 255)::text,
  'blocked',
  'Payload info...',
  now() - (interval '1 minute' * floor(random() * 1440))
from generate_series(1, 15);
